LineLength:
  Max: 80
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

SingleSpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false
