LineLength:
  Max: 100
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

Metrics/BlockLength:
  Max: 80

SpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false
